### ISSUE TITLE
bad/missing install instructions

### ISSUE THREAD

**Issue by ianfoster** [CODARcode/savanna#1]
1) The two paragraphs starting "The simplest form of installation is through spack" have two URLs, both of which are different from the text and neither of which work:   
   https://github.com/LLNL/spack -- references https://github.com/CODARcode/savanna/blob/master
   https://github.com/CODARcode/spack -- references https://github.com/CODARcode/savanna/blob/master

2) The documentation does not tell how to install spack, which seems to require some specialized instructions to use your specific branch. For me, these seemed to be as follows:

git clone  https://github.com/CODARcode/spack
. spack/share/spack/setup-env.sh
cd spack
git checkout -t origin/codar
spack install savanna

Thanks -- Ian

**Comment by kshitij-v-mehta** [comment]
This is now fixed.
